import type { Metadata } from 'next';
import { Inter, Montserrat } from 'next/font/google';
import './globals.css';
import Providers from '@/Providers/Providers';

const inter = Inter({ subsets: ['latin'], weight: '400' });
const montserrat = Montserrat({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
      title: 'Furbabyz Drip',
      description: 'Generated by create next app',
};

export default function RootLayout({
      children,
}: Readonly<{
      children: React.ReactNode;
}>) {
      return (
            <html lang="en">
                  <body className={`${inter.className} ${montserrat.className}`}>
                        <Providers>{children}</Providers>
                  </body>
            </html>
      );
}
